apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hub
  namespace: {{ .Release.Namespace }}
  labels:
    app: jupyterhub
    app.kubernetes.io/managed-by: Helm
    chart: jupyterhub-1.0.1
    component: hub
    heritage: Helm
    release: dhub-{{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: dhub-{{ .Release.Namespace }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods", "persistentvolumeclaims", "secrets", "services"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["events"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hub
  namespace: {{ .Release.Namespace }}
  labels:
    app: jupyterhub
    app.kubernetes.io/managed-by: Helm
    chart: jupyterhub-1.0.1
    component: hub
    heritage: Helm
    release: dhub-{{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: dhub-{{ .Release.Namespace }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: hub
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autohttps
  namespace: {{ .Release.Namespace }}
  labels:
    app: jupyterhub
    app.kubernetes.io/managed-by: Helm
    chart: jupyterhub-1.0.1
    component: autohttps
    heritage: Helm
    release: dhub-{{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: dhub-{{ .Release.Namespace }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "patch", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autohttps
  namespace: {{ .Release.Namespace }}
  labels:
    app: jupyterhub
    app.kubernetes.io/managed-by: Helm
    chart: jupyterhub-1.0.1
    component: autohttps
    heritage: Helm
    release: dhub-{{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: dhub-{{ .Release.Namespace }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: autohttps
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: autohttps
